name: Source git Automation
on:
  workflow_run:
    workflows: [ Gather Pull Request Metadata ]
    types:
      - completed

permissions:
  contents: read

jobs:
  download-metadata:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    outputs:
      pr-metadata: ${{ steps.Artifact.outputs.pr-metadata-json }}

    steps:
      - id: Artifact
        name: Download Artifact
        uses: redhat-plumbers-in-action/download-artifact@v1
        with:
          name: Pull Request Metadata

  source-git-automation:
    needs: [ download-metadata ]
    runs-on: ubuntu-latest

    permissions:
      # required for merging PRs
      contents: write
      # required for PR comments and setting labels
      pull-requests: write

    steps:
      - name: Source-git Automation
        uses: jamacku/source-git-automation@main
        with:
          pr-metadata: ${{ needs.download-metadata.outputs.pr-metadata }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
          gemini-api-token: ${{ secrets.GEMINI_API_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
